### ISSUE TITLE
Turn this into a consumable package

### ISSUE THREAD

**Issue by philkunz** [KNawm/speed-cloudflare-cli#11]
Hi, this is a super cool package. However, right now, it is not built for consumability.
What do you think about making this consumable in third party modules?

Regards
Phil

**Comment by KNawm** [comment]
Hey Phil, that's a good idea, are you interested in opening a PR?

**Comment by philkunz** [comment]
I can, however if I do that, and spend the time going through the code, I'd do a rewrite of the module towards TypeScript and turn it into proper classes. Is that something you'd be ok with?

**Comment by KNawm** [comment]
Not really, while this would be nice to add into the functionality, this package was designed to be primarily used with `npx` so zero dependencies is a must. However, if you have a specific use case for this, feel free to reuse the code as this project is MIT-licensed.

**Comment by philkunz** [comment]
I took some code of this repo and mentioned you in the accompanying MIT license accordingly:
https://gitlab.com/pushrocks/smartnetwork/-/blob/master/license
