### ISSUE TITLE
Measure the Jitter

### ISSUE THREAD

**Issue by sibirajal** [KNawm/speed-cloudflare-cli#9]
Hello Tomás, 

Thank you for developing a CLI tool for the Cloudflare speed test. 

There is a jitter value presented in https://speed.cloudflare.com/. 

Would it be possible to add the Jitter value additional to the existing values? 

That would be really helpful to measure the latency-sensitive issues.

**Comment by roscoejp** [comment]
The UI tooltip for jitter describes it as:

> the average distance between consecutive latency measurements. Lower jitter is better.

Since the latency test already has 10 results you should be able to get the absolute value of differences between each consecutive run and then average that list pretty easily. Patch above should take care of it.

**Comment by KNawm** [comment]
Implemented in #10
